from .listagem_repository_jokes import listagem_repository_jokes
from .listagem_repository_categories import listagem_repository_categories
from .historico_repository_jokes import historico_repository_jokes